<a href="https://colab.research.google.com/github/Rguarnizo/MoviliApp/blob/master/TransmilenioMVA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#MoviliApp Y Transmilenio

## Datos Estaciones y Rutas.

In [1]:
import pandas as pd
import numpy as np

In [2]:
Rutas = pd.read_csv("/content/drive/My Drive/UniversidadNacional/2020-1CuartoSemestre/EstructurasDeDatos/Data Structures MoviliApp/Datos/Estaciones_Troncales_de_TRANSMILENIO.csv")
Estaciones = pd.read_csv("/content/drive/My Drive/UniversidadNacional/2020-1CuartoSemestre/EstructurasDeDatos/Data Structures MoviliApp/Datos/Estaciones_Troncales_de_TRANSMILENIO.csv")

In [3]:
Rutas

     objectid  ...                                globalid
0           1  ...  {D804EEAA-1DFA-41B9-8EA7-4C5C728E7AC1}
1           2  ...  {182C5CE1-0696-47CA-8EB8-40E45A851D42}
2           3  ...  {D51603ED-7B42-48F9-A729-98A88E48C3CA}
3           4  ...  {43A41E08-B32C-458F-B86F-76D19888C696}
4           5  ...  {893AC347-B878-48AD-A615-F94C152AFF8C}
..        ...  ...                                     ...
144       145  ...  {1282A081-32B9-47F1-9E6E-880DA10D7440}
145       146  ...  {82510740-6123-44A5-860A-30C4A63D9617}
146       147  ...  {C1A7183F-2271-4DA4-BF68-D7656692280E}
147       148  ...  {4F280485-DDAB-4835-BCB9-BAA6DD6B4D7D}
148       149  ...  {80AC961D-9AE5-44E7-AA30-4329A3BDF607}

[149 rows x 16 columns]

In [4]:
Estaciones

     objectid  ...                                globalid
0           1  ...  {D804EEAA-1DFA-41B9-8EA7-4C5C728E7AC1}
1           2  ...  {182C5CE1-0696-47CA-8EB8-40E45A851D42}
2           3  ...  {D51603ED-7B42-48F9-A729-98A88E48C3CA}
3           4  ...  {43A41E08-B32C-458F-B86F-76D19888C696}
4           5  ...  {893AC347-B878-48AD-A615-F94C152AFF8C}
..        ...  ...                                     ...
144       145  ...  {1282A081-32B9-47F1-9E6E-880DA10D7440}
145       146  ...  {82510740-6123-44A5-860A-30C4A63D9617}
146       147  ...  {C1A7183F-2271-4DA4-BF68-D7656692280E}
147       148  ...  {4F280485-DDAB-4835-BCB9-BAA6DD6B4D7D}
148       149  ...  {80AC961D-9AE5-44E7-AA30-4329A3BDF607}

[149 rows x 16 columns]

In [5]:
Rutas.to_json("RutasTransmilenio.json")

In [6]:
Estaciones.to_json("EstacionesTransmilenio.json")

In [7]:
RutasTM = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Datos/Rutas_Troncales_de_TRANSMILENIO.csv")

In [8]:
RutasTM

     objectid  ... st_lengthshape
0           1  ...   10173.328001
1           2  ...   31219.534774
2           3  ...   22363.274654
3           6  ...    7867.140501
4           7  ...   12084.823846
..        ...  ...            ...
103       116  ...   15335.556452
104       117  ...   27549.481822
105       118  ...   19174.260499
106       119  ...   22587.391916
107       120  ...   31650.959843

[108 rows x 10 columns]

In [9]:
EstacionesTM = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Datos/Estaciones_Troncales_de_TRANSMILENIO.csv")

In [10]:
EstacionesTM

             X  ...                                globalid
0   -74.056178  ...  {D804EEAA-1DFA-41B9-8EA7-4C5C728E7AC1}
1   -74.046035  ...  {182C5CE1-0696-47CA-8EB8-40E45A851D42}
2   -74.079866  ...  {D51603ED-7B42-48F9-A729-98A88E48C3CA}
3   -74.055298  ...  {43A41E08-B32C-458F-B86F-76D19888C696}
4   -74.049218  ...  {893AC347-B878-48AD-A615-F94C152AFF8C}
..         ...  ...                                     ...
144 -74.104640  ...  {1282A081-32B9-47F1-9E6E-880DA10D7440}
145 -74.077406  ...  {82510740-6123-44A5-860A-30C4A63D9617}
146 -74.090338  ...  {C1A7183F-2271-4DA4-BF68-D7656692280E}
147 -74.086921  ...  {4F280485-DDAB-4835-BCB9-BAA6DD6B4D7D}
148 -74.181225  ...  {80AC961D-9AE5-44E7-AA30-4329A3BDF607}

[149 rows x 18 columns]

In [12]:
EstacionesTM.columns

Index(['X', 'Y', 'objectid', 'numero_estacion', 'nombre_estacion',
       'coordenada_x_estacion', 'coordenada_y_estacion', 'ubicacion_estacion',
       'troncal_estacion', 'numero_vagones_estacion',
       'numero_accesos_estacion', 'biciestacion_estacion',
       'capacidad_biciestacion_estacion', 'tipo_estacion',
       'biciparqueadero_estacion', 'latitud_estacion', 'longitud_estacion',
       'globalid'],
      dtype='object')

In [13]:
EstacionesFiltradas = EstacionesTM[["nombre_estacion","numero_vagones_estacion","numero_accesos_estacion","latitud_estacion","longitud_estacion"]]

In [14]:
EstacionesFiltradas.to_json("EstacionesFiltradas.json",orient='records')
EstacionesFiltradas

      nombre_estacion  ...  longitud_estacion
0           Calle 106  ...         -74.056147
1    Portal del Norte  ...         -74.045965
2       AV. El Dorado  ...         -74.079769
3         Pepe Sierra  ...         -74.055313
4             Mazur√©n  ...         -74.048970
..                ...  ...                ...
144     Puente Aranda  ...         -74.104614
145     San Victorino  ...         -74.076854
146     Ciudad Jard√≠n  ...         -74.090428
147         Policarpa  ...         -74.086550
148              Bosa  ...         -74.179184

[149 rows x 5 columns]

In [16]:
RutasTMFiltradas = RutasTM[["route_name_ruta_troncal","origen_ruta_troncal","destino_ruta_troncal"]]
RutasTMFiltradas

    route_name_ruta_troncal origen_ruta_troncal destino_ruta_troncal
0                       A74             Toberin             Calle 72
1                       B14     Portal Americas         Portal Norte
2                       B23     Portal Eldorado               Alcal√°
3                       B55           Portal 80               Heroes
4                       B56              Heroes          Portal Suba
..                      ...                 ...                  ...
103                     6-1           Portal 80        Universidades
104                     B52     Portal Americas               Alcala
105                     7-2        Santa Isabel          Portal Suba
106                     B50         Portal Suba            Calle 161
107                     B44          Portal Sur         Portal Norte

[108 rows x 3 columns]

In [ ]:
RutasTMFiltradas

In [ ]:
RutasEstacionesTM = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Datos/RutasEstacionesTM.csv",encoding='latin1')

In [ ]:
RutasEstacionesTM

In [ ]:
RutasEstacionesTM = RutasEstacionesTM.drop(columns=['Tipo Servicio','Nodo','L√≠nea']);

In [ ]:
EstacionesRutasTM = RutasEstacionesTM.groupby('Nombre Nodo',as_index=False).agg(list);

In [ ]:
EstacionesRutasTM

In [ ]:
RutasEstacionesTM = RutasEstacionesTM.groupby('Ruta',as_index=False).agg(list)
RutasEstacionesTM

In [ ]:
RutasEstacionesTM = RutasEstacionesTM.rename(columns={'Posici√≥n': 'Position','Nombre Nodo':'ListaParadas'})
EstacionesRutasTM = EstacionesRutasTM.rename(columns={'Nombre Nodo': 'Estacion','Ruta':'Rutas'})

In [ ]:
Rutas = pd.Series([element.lstrip("[1234567890]") for element in RutasEstacionesTM['Ruta']])

In [ ]:
Rutas = pd.Series([element.rstrip("abcdefghijklmenoprstuvwxyzABCDEFGHIJKLMNOPQRSTUWVXYZ. ") for element in Rutas])

In [ ]:
Rutas = pd.Series([element.lstrip(" -") for element in Rutas])

In [ ]:
Rutas = pd.Series([element.rstrip("- ") for element in Rutas])

In [ ]:
RutasEstacionesTM['Ruta'] = Rutas

In [ ]:
RutasParadasTM = RutasEstacionesTM.drop(columns={'Rutas'})
RutasParadasTM.to_json("RutasParadasTM.json",orient='records')

In [ ]:
RutasEstacionesTM['Ruta']

In [ ]:
type(RutasEstacionesTM['Ruta'])

In [ ]:
RutasEstacionesTM.to_json("JsonRutasListEsta.json",orient='records')
EstacionesRutasTM.to_json("JsonEstacionesListRutas.json",orient='records')